[google_service_account]
type = "service_account"
project_id = "sonic-aria-462204-e7"
private_key_id = "db18629740cc86742105fcf41bb42782457bb17e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC6Pxl88hAHisId
d2suUD6IQveu6VBgt8gfY5ZQLPxWu7fBo4XfCydNf+xWqIVgBaEy+z4UJupmMp99
LbOe4+2re0nseSmSlZcN5xlUntvjyiQpHS3YxfzvXwAX+VAcvGt4NuHP2ZIuWg6h
ssy/rf6cx7S8NJmI0JqtF2xnc0C4ONLnEGQAUCfxNjDhk6+6Qg/qhRopnSJdZumD
wlaI5y5Lz4FUlMJKHEN/Qfyw9j1tSGF87rcwG6l9w5xDrdhYyeCVbCqWUghstSMz
5RY1/by4L0YqdI4XegfNC7aSMDQ1zrWh429XVDMIGixc6dX0eiBZwm4eu6TtlHBE
Fb7dj0XZAgMBAAECggEAAlE3EJGBo4zInec9EFlzpB+Sx1YkNHl05ipHorDvy5oQ
Twd2BFcC/F+proMjdBT92XPvMZiX9M31ozzgIQtciw3aPWf26kAt0ScQu9D++WMr
3TSwu/BSrx1ZrSXiWkktD4gKegFbl6bYZPVwvx3Ie8wV5cjEJ3cFxaUmwyHxXZlj
iKvlyOPSS5fXeYyu6rbIhBV8fLh+jlYP8V3sj9Gjc1dTomO7RSnkt9GgUAITqbZs
XSui0TFnUzlC+u1fQ45p9Cb6X6wzGn1woKt2RiotVVB9ZCp0AeHfIrOlO9aSDcyq
5s4UGXhFSLl9EkM1kBdV0Kalpfpdpla1+D2sFd4/1QKBgQDw35hL6cel8VrnnqEu
VAKOpyT7FO8UCq2oXZD7WHfNhxnqKx/NlBi6gzdgmZnFP8NqCXWv/+lUcnAClSku
uKRpP4D+TUs9PTtovHUnaCIExpjCrSumRvmktAnIvYlJIqUFcRVmsOijOBOQh+v3
RDuNyRm1I8aZB/fZFh6T8idw7wKBgQDF8Us+VPIgmwiZoxgIpxR7x3zTelhCTgIx
cTUVUgc/jueEaeQ0CZm0xxAoKvSXIyG7fMQRSd8o1KO4hAYD8R9nVaBJR2b/VjxI
FtYMjw0KrIKjbsQcQ/Mp90tqQbgYGwlRqsBwJXTOetOfnWVnms1Dg+SYIfI2T52f
u/x3GqUltwKBgQCzxh2zosLYTj+LmTAxFJBoCcWnA6PAMIwVmefIP+oCYm/r/s2Y
sIyYP7DIDzveJM3jSTYl6nkqBtMkilEXRsWmq7fJlMSv6xB5BhbmF2k0aUjAG2D1
lAlkbN7UjOl2xT2mxxSy9RxcHVE00M1DWhCcrNfcAtyJgJHx2vltcBERzwKBgHk2
HWF6GxskVMvgN6N0zPJPYn0N+mX/5w/nxx3bMV0WYWeQgJHtHxa4n4g5ZbX3aXyq
FlaP6fvS2r7u+dAII7bflFvLQaMyZ4+tjD38i3vxz73M4oJ8ibc1HBVhUR5R0A8W
hOknxrN6O4UOmT4saW3iomUWxH/FmTxrnVpCEsdZAoGBAIl1KHBb6L2q8MiaFRUJ
3NkzRfNyC05S4IfveiVo9D5oCSosqhySf+eSLe1fBcVWLUF4v1UfLzbuobZNotPR
Z8Ai18+cNh/l3YOsUzeIqm+LVC1av1KXLBMArYMB6tILrDpv2lQ0XmxwiDykbm+t
/qIBf4jSxSed0qYG87AiwfvM
-----END PRIVATE KEY-----"""
client_email = "streamlit-app@sonic-aria-462204-e7.iam.gserviceaccount.com"
client_id = "118126310741221448830"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-app%40sonic-aria-462204-e7.iam.gserviceaccount.com"
